--
-- PostgreSQL database dump
--

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.2

-- Started on 2025-11-04 17:16:19 IST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4414 (class 1262 OID 24812)
-- Name: rivollo-dev-db; Type: DATABASE; Schema: -; Owner: -
--

CREATE DATABASE "rivollo-dev-db" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


\connect -reuse-previous=on "dbname='rivollo-dev-db'"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- TOC entry 4415 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- TOC entry 888 (class 1247 OID 24824)
-- Name: blueprint_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.blueprint_status AS ENUM (
    'processing',
    'ready',
    'failed'
);


--
-- TOC entry 885 (class 1247 OID 24814)
-- Name: job_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.job_status AS ENUM (
    'queued',
    'processing',
    'ready',
    'failed'
);


--
-- TOC entry 243 (class 1255 OID 24960)
-- Name: trg_set_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.trg_set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 237 (class 1259 OID 25357)
-- Name: tbl_activity_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_activity_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    actor_user_id uuid,
    org_id uuid,
    target_type text NOT NULL,
    target_id uuid,
    action text NOT NULL,
    ip text,
    user_agent text,
    occurred_at timestamp with time zone DEFAULT now() NOT NULL,
    metadata text,
    created_by uuid,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_date timestamp with time zone
);


--
-- TOC entry 233 (class 1259 OID 25288)
-- Name: tbl_analytics_daily_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_analytics_daily_product (
    day date NOT NULL,
    org_id uuid,
    product_id uuid NOT NULL,
    views integer DEFAULT 0 NOT NULL,
    engaged integer DEFAULT 0 NOT NULL,
    adds_from_3d integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_date timestamp with time zone
);


--
-- TOC entry 232 (class 1259 OID 25260)
-- Name: tbl_analytics_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_analytics_events (
    id integer NOT NULL,
    org_id uuid,
    product_id uuid,
    publish_link_id uuid,
    event_type text NOT NULL,
    occurred_at timestamp with time zone DEFAULT now() NOT NULL,
    payload text,
    created_by uuid,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_date timestamp with time zone
);


--
-- TOC entry 231 (class 1259 OID 25259)
-- Name: tbl_analytics_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbl_analytics_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_analytics_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 25104)
-- Name: tbl_assets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_assets (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    type text NOT NULL,
    url text NOT NULL,
    mime_type text,
    size_bytes integer,
    created_by uuid,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_date timestamp with time zone
);


--
-- TOC entry 234 (class 1259 OID 25307)
-- Name: tbl_auth_identities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_auth_identities (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    provider text NOT NULL,
    provider_user_id text NOT NULL,
    email text,
    last_login_at timestamp with time zone,
    meta text,
    created_by uuid,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_date timestamp with time zone
);


--
-- TOC entry 225 (class 1259 OID 25145)
-- Name: tbl_configurators; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_configurators (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    product_id uuid NOT NULL,
    settings text,
    created_by uuid,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_date timestamp with time zone
);


--
-- TOC entry 235 (class 1259 OID 25325)
-- Name: tbl_email_verifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_email_verifications (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    token text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_by uuid,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_date timestamp with time zone
);


--
-- TOC entry 229 (class 1259 OID 25220)
-- Name: tbl_galleries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_galleries (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    is_public boolean DEFAULT false NOT NULL,
    created_by uuid,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_date timestamp with time zone
);


--
-- TOC entry 230 (class 1259 OID 25238)
-- Name: tbl_gallery_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_gallery_items (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    gallery_id uuid NOT NULL,
    product_id uuid NOT NULL,
    order_index integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_date timestamp with time zone
);


--
-- TOC entry 226 (class 1259 OID 25159)
-- Name: tbl_hotspots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_hotspots (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    product_id uuid NOT NULL,
    label text,
    description text,
    pos_x double precision NOT NULL,
    pos_y double precision NOT NULL,
    pos_z double precision NOT NULL,
    text_font text,
    text_color text,
    bg_color text,
    action_type text,
    action_payload text,
    order_index integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_date timestamp with time zone
);


--
-- TOC entry 227 (class 1259 OID 25177)
-- Name: tbl_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_jobs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    product_id uuid NOT NULL,
    image_asset_id uuid,
    model_asset_id uuid,
    status text NOT NULL,
    engine text,
    completed_at timestamp with time zone,
    created_by uuid,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_date timestamp with time zone
);


--
-- TOC entry 222 (class 1259 OID 25082)
-- Name: tbl_license_assignments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_license_assignments (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    subscription_id uuid NOT NULL,
    user_id uuid NOT NULL,
    status text NOT NULL,
    limits text,
    usage_counters text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_date timestamp with time zone
);


--
-- TOC entry 220 (class 1259 OID 25051)
-- Name: tbl_mstr_plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_mstr_plans (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    quotas text,
    created_by uuid,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_date timestamp with time zone
);


--
-- TOC entry 238 (class 1259 OID 25379)
-- Name: tbl_notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_notifications (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    type text NOT NULL,
    title text NOT NULL,
    body text,
    data text,
    read_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_date timestamp with time zone
);


--
-- TOC entry 219 (class 1259 OID 25033)
-- Name: tbl_org_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_org_members (
    org_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role text NOT NULL,
    created_by uuid,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_date timestamp with time zone
);


--
-- TOC entry 218 (class 1259 OID 25023)
-- Name: tbl_organizations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_organizations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    branding text,
    created_by uuid,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_date timestamp with time zone
);


--
-- TOC entry 236 (class 1259 OID 25341)
-- Name: tbl_password_resets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_password_resets (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    token text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_by uuid,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_date timestamp with time zone
);


--
-- TOC entry 224 (class 1259 OID 25118)
-- Name: tbl_products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_products (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    status text NOT NULL,
    model_asset_id uuid,
    created_by uuid,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_date timestamp with time zone
);


--
-- TOC entry 228 (class 1259 OID 25202)
-- Name: tbl_publish_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_publish_links (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    product_id uuid NOT NULL,
    public_id text NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    expires_at timestamp with time zone,
    password_hash text,
    created_by uuid,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_date timestamp with time zone
);


--
-- TOC entry 221 (class 1259 OID 25061)
-- Name: tbl_subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_subscriptions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    plan_id uuid NOT NULL,
    status text NOT NULL,
    seats_purchased integer DEFAULT 1 NOT NULL,
    billing text,
    current_period_start timestamp with time zone,
    current_period_end timestamp with time zone,
    created_by uuid,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_date timestamp with time zone
);


--
-- TOC entry 239 (class 1259 OID 25396)
-- Name: tbl_user_notification_prefs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_user_notification_prefs (
    user_id uuid NOT NULL,
    channels text,
    muted_types text,
    created_by uuid,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_date timestamp with time zone
);


--
-- TOC entry 217 (class 1259 OID 25012)
-- Name: tbl_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email text NOT NULL,
    password_hash text,
    name text,
    avatar_url text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_date timestamp with time zone
);


--
-- TOC entry 4406 (class 0 OID 25357)
-- Dependencies: 237
-- Data for Name: tbl_activity_logs; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tbl_activity_logs (id, actor_user_id, org_id, target_type, target_id, action, ip, user_agent, occurred_at, metadata, created_by, created_date, updated_by, updated_date) FROM stdin;
\.


--
-- TOC entry 4402 (class 0 OID 25288)
-- Dependencies: 233
-- Data for Name: tbl_analytics_daily_product; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tbl_analytics_daily_product (day, org_id, product_id, views, engaged, adds_from_3d, created_by, created_date, updated_by, updated_date) FROM stdin;
\.


--
-- TOC entry 4401 (class 0 OID 25260)
-- Dependencies: 232
-- Data for Name: tbl_analytics_events; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tbl_analytics_events (id, org_id, product_id, publish_link_id, event_type, occurred_at, payload, created_by, created_date, updated_by, updated_date) FROM stdin;
\.


--
-- TOC entry 4392 (class 0 OID 25104)
-- Dependencies: 223
-- Data for Name: tbl_assets; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tbl_assets (id, org_id, type, url, mime_type, size_bytes, created_by, created_date, updated_by, updated_date) FROM stdin;
\.


--
-- TOC entry 4403 (class 0 OID 25307)
-- Dependencies: 234
-- Data for Name: tbl_auth_identities; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tbl_auth_identities (id, user_id, provider, provider_user_id, email, last_login_at, meta, created_by, created_date, updated_by, updated_date) FROM stdin;
\.


--
-- TOC entry 4394 (class 0 OID 25145)
-- Dependencies: 225
-- Data for Name: tbl_configurators; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tbl_configurators (id, product_id, settings, created_by, created_date, updated_by, updated_date) FROM stdin;
\.


--
-- TOC entry 4404 (class 0 OID 25325)
-- Dependencies: 235
-- Data for Name: tbl_email_verifications; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tbl_email_verifications (id, user_id, token, expires_at, used_at, created_by, created_date, updated_by, updated_date) FROM stdin;
\.


--
-- TOC entry 4398 (class 0 OID 25220)
-- Dependencies: 229
-- Data for Name: tbl_galleries; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tbl_galleries (id, org_id, name, slug, is_public, created_by, created_date, updated_by, updated_date) FROM stdin;
\.


--
-- TOC entry 4399 (class 0 OID 25238)
-- Dependencies: 230
-- Data for Name: tbl_gallery_items; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tbl_gallery_items (id, gallery_id, product_id, order_index, created_by, created_date, updated_by, updated_date) FROM stdin;
\.


--
-- TOC entry 4395 (class 0 OID 25159)
-- Dependencies: 226
-- Data for Name: tbl_hotspots; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tbl_hotspots (id, product_id, label, description, pos_x, pos_y, pos_z, text_font, text_color, bg_color, action_type, action_payload, order_index, created_at, created_by, created_date, updated_by, updated_date) FROM stdin;
\.


--
-- TOC entry 4396 (class 0 OID 25177)
-- Dependencies: 227
-- Data for Name: tbl_jobs; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tbl_jobs (id, product_id, image_asset_id, model_asset_id, status, engine, completed_at, created_by, created_date, updated_by, updated_date) FROM stdin;
\.


--
-- TOC entry 4391 (class 0 OID 25082)
-- Dependencies: 222
-- Data for Name: tbl_license_assignments; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tbl_license_assignments (id, subscription_id, user_id, status, limits, usage_counters, created_at, created_by, created_date, updated_by, updated_date) FROM stdin;
\.


--
-- TOC entry 4389 (class 0 OID 25051)
-- Dependencies: 220
-- Data for Name: tbl_mstr_plans; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tbl_mstr_plans (id, code, name, quotas, created_by, created_date, updated_by, updated_date) FROM stdin;
\.


--
-- TOC entry 4407 (class 0 OID 25379)
-- Dependencies: 238
-- Data for Name: tbl_notifications; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tbl_notifications (id, user_id, type, title, body, data, read_at, created_at, created_by, created_date, updated_by, updated_date) FROM stdin;
\.


--
-- TOC entry 4388 (class 0 OID 25033)
-- Dependencies: 219
-- Data for Name: tbl_org_members; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tbl_org_members (org_id, user_id, role, created_by, created_date, updated_by, updated_date) FROM stdin;
\.


--
-- TOC entry 4387 (class 0 OID 25023)
-- Dependencies: 218
-- Data for Name: tbl_organizations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tbl_organizations (id, name, slug, branding, created_by, created_date, updated_by, updated_date) FROM stdin;
\.


--
-- TOC entry 4405 (class 0 OID 25341)
-- Dependencies: 236
-- Data for Name: tbl_password_resets; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tbl_password_resets (id, user_id, token, expires_at, used_at, created_by, created_date, updated_by, updated_date) FROM stdin;
\.


--
-- TOC entry 4393 (class 0 OID 25118)
-- Dependencies: 224
-- Data for Name: tbl_products; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tbl_products (id, org_id, name, slug, status, model_asset_id, created_by, created_date, updated_by, updated_date) FROM stdin;
\.


--
-- TOC entry 4397 (class 0 OID 25202)
-- Dependencies: 228
-- Data for Name: tbl_publish_links; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tbl_publish_links (id, product_id, public_id, is_enabled, expires_at, password_hash, created_by, created_date, updated_by, updated_date) FROM stdin;
\.


--
-- TOC entry 4390 (class 0 OID 25061)
-- Dependencies: 221
-- Data for Name: tbl_subscriptions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tbl_subscriptions (id, user_id, plan_id, status, seats_purchased, billing, current_period_start, current_period_end, created_by, created_date, updated_by, updated_date) FROM stdin;
\.


--
-- TOC entry 4408 (class 0 OID 25396)
-- Dependencies: 239
-- Data for Name: tbl_user_notification_prefs; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tbl_user_notification_prefs (user_id, channels, muted_types, created_by, created_date, updated_by, updated_date) FROM stdin;
\.


--
-- TOC entry 4386 (class 0 OID 25012)
-- Dependencies: 217
-- Data for Name: tbl_users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tbl_users (id, email, password_hash, name, avatar_url, created_at, created_by, created_date, updated_by, updated_date) FROM stdin;
\.


--
-- TOC entry 4416 (class 0 OID 0)
-- Dependencies: 231
-- Name: tbl_analytics_events_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.tbl_analytics_events_id_seq', 1, false);


--
-- TOC entry 4159 (class 2606 OID 25365)
-- Name: tbl_activity_logs tbl_activity_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_activity_logs
    ADD CONSTRAINT tbl_activity_logs_pkey PRIMARY KEY (id);


--
-- TOC entry 4137 (class 2606 OID 25295)
-- Name: tbl_analytics_daily_product tbl_analytics_daily_product_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_analytics_daily_product
    ADD CONSTRAINT tbl_analytics_daily_product_pkey PRIMARY KEY (day, product_id);


--
-- TOC entry 4134 (class 2606 OID 25267)
-- Name: tbl_analytics_events tbl_analytics_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_analytics_events
    ADD CONSTRAINT tbl_analytics_events_pkey PRIMARY KEY (id);


--
-- TOC entry 4091 (class 2606 OID 25111)
-- Name: tbl_assets tbl_assets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_assets
    ADD CONSTRAINT tbl_assets_pkey PRIMARY KEY (id);


--
-- TOC entry 4140 (class 2606 OID 25314)
-- Name: tbl_auth_identities tbl_auth_identities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_auth_identities
    ADD CONSTRAINT tbl_auth_identities_pkey PRIMARY KEY (id);


--
-- TOC entry 4142 (class 2606 OID 25316)
-- Name: tbl_auth_identities tbl_auth_identities_provider_provider_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_auth_identities
    ADD CONSTRAINT tbl_auth_identities_provider_provider_user_id_key UNIQUE (provider, provider_user_id);


--
-- TOC entry 4144 (class 2606 OID 25318)
-- Name: tbl_auth_identities tbl_auth_identities_user_id_provider_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_auth_identities
    ADD CONSTRAINT tbl_auth_identities_user_id_provider_key UNIQUE (user_id, provider);


--
-- TOC entry 4100 (class 2606 OID 25152)
-- Name: tbl_configurators tbl_configurators_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_configurators
    ADD CONSTRAINT tbl_configurators_pkey PRIMARY KEY (id);


--
-- TOC entry 4147 (class 2606 OID 25332)
-- Name: tbl_email_verifications tbl_email_verifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_email_verifications
    ADD CONSTRAINT tbl_email_verifications_pkey PRIMARY KEY (id);


--
-- TOC entry 4149 (class 2606 OID 25334)
-- Name: tbl_email_verifications tbl_email_verifications_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_email_verifications
    ADD CONSTRAINT tbl_email_verifications_token_key UNIQUE (token);


--
-- TOC entry 4119 (class 2606 OID 25230)
-- Name: tbl_galleries tbl_galleries_org_id_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_galleries
    ADD CONSTRAINT tbl_galleries_org_id_slug_key UNIQUE (org_id, slug);


--
-- TOC entry 4121 (class 2606 OID 25228)
-- Name: tbl_galleries tbl_galleries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_galleries
    ADD CONSTRAINT tbl_galleries_pkey PRIMARY KEY (id);


--
-- TOC entry 4125 (class 2606 OID 25246)
-- Name: tbl_gallery_items tbl_gallery_items_gallery_id_product_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_gallery_items
    ADD CONSTRAINT tbl_gallery_items_gallery_id_product_id_key UNIQUE (gallery_id, product_id);


--
-- TOC entry 4127 (class 2606 OID 25244)
-- Name: tbl_gallery_items tbl_gallery_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_gallery_items
    ADD CONSTRAINT tbl_gallery_items_pkey PRIMARY KEY (id);


--
-- TOC entry 4103 (class 2606 OID 25168)
-- Name: tbl_hotspots tbl_hotspots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_hotspots
    ADD CONSTRAINT tbl_hotspots_pkey PRIMARY KEY (id);


--
-- TOC entry 4105 (class 2606 OID 25170)
-- Name: tbl_hotspots tbl_hotspots_product_id_order_index_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_hotspots
    ADD CONSTRAINT tbl_hotspots_product_id_order_index_key UNIQUE (product_id, order_index);


--
-- TOC entry 4109 (class 2606 OID 25184)
-- Name: tbl_jobs tbl_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_jobs
    ADD CONSTRAINT tbl_jobs_pkey PRIMARY KEY (id);


--
-- TOC entry 4086 (class 2606 OID 25090)
-- Name: tbl_license_assignments tbl_license_assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_license_assignments
    ADD CONSTRAINT tbl_license_assignments_pkey PRIMARY KEY (id);


--
-- TOC entry 4088 (class 2606 OID 25092)
-- Name: tbl_license_assignments tbl_license_assignments_subscription_id_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_license_assignments
    ADD CONSTRAINT tbl_license_assignments_subscription_id_user_id_key UNIQUE (subscription_id, user_id);


--
-- TOC entry 4077 (class 2606 OID 25060)
-- Name: tbl_mstr_plans tbl_mstr_plans_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_mstr_plans
    ADD CONSTRAINT tbl_mstr_plans_code_key UNIQUE (code);


--
-- TOC entry 4079 (class 2606 OID 25058)
-- Name: tbl_mstr_plans tbl_mstr_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_mstr_plans
    ADD CONSTRAINT tbl_mstr_plans_pkey PRIMARY KEY (id);


--
-- TOC entry 4164 (class 2606 OID 25387)
-- Name: tbl_notifications tbl_notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_notifications
    ADD CONSTRAINT tbl_notifications_pkey PRIMARY KEY (id);


--
-- TOC entry 4075 (class 2606 OID 25039)
-- Name: tbl_org_members tbl_org_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_org_members
    ADD CONSTRAINT tbl_org_members_pkey PRIMARY KEY (org_id, user_id);


--
-- TOC entry 4070 (class 2606 OID 25030)
-- Name: tbl_organizations tbl_organizations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_organizations
    ADD CONSTRAINT tbl_organizations_pkey PRIMARY KEY (id);


--
-- TOC entry 4072 (class 2606 OID 25032)
-- Name: tbl_organizations tbl_organizations_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_organizations
    ADD CONSTRAINT tbl_organizations_slug_key UNIQUE (slug);


--
-- TOC entry 4152 (class 2606 OID 25348)
-- Name: tbl_password_resets tbl_password_resets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_password_resets
    ADD CONSTRAINT tbl_password_resets_pkey PRIMARY KEY (id);


--
-- TOC entry 4154 (class 2606 OID 25350)
-- Name: tbl_password_resets tbl_password_resets_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_password_resets
    ADD CONSTRAINT tbl_password_resets_token_key UNIQUE (token);


--
-- TOC entry 4095 (class 2606 OID 25127)
-- Name: tbl_products tbl_products_org_id_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_products
    ADD CONSTRAINT tbl_products_org_id_slug_key UNIQUE (org_id, slug);


--
-- TOC entry 4097 (class 2606 OID 25125)
-- Name: tbl_products tbl_products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_products
    ADD CONSTRAINT tbl_products_pkey PRIMARY KEY (id);


--
-- TOC entry 4113 (class 2606 OID 25210)
-- Name: tbl_publish_links tbl_publish_links_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_publish_links
    ADD CONSTRAINT tbl_publish_links_pkey PRIMARY KEY (id);


--
-- TOC entry 4115 (class 2606 OID 25212)
-- Name: tbl_publish_links tbl_publish_links_public_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_publish_links
    ADD CONSTRAINT tbl_publish_links_public_id_key UNIQUE (public_id);


--
-- TOC entry 4083 (class 2606 OID 25069)
-- Name: tbl_subscriptions tbl_subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_subscriptions
    ADD CONSTRAINT tbl_subscriptions_pkey PRIMARY KEY (id);


--
-- TOC entry 4166 (class 2606 OID 25402)
-- Name: tbl_user_notification_prefs tbl_user_notification_prefs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_user_notification_prefs
    ADD CONSTRAINT tbl_user_notification_prefs_pkey PRIMARY KEY (user_id);


--
-- TOC entry 4066 (class 2606 OID 25022)
-- Name: tbl_users tbl_users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_users
    ADD CONSTRAINT tbl_users_email_key UNIQUE (email);


--
-- TOC entry 4068 (class 2606 OID 25020)
-- Name: tbl_users tbl_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_users
    ADD CONSTRAINT tbl_users_pkey PRIMARY KEY (id);


--
-- TOC entry 4155 (class 1259 OID 25377)
-- Name: idx_activity_logs_actor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_activity_logs_actor ON public.tbl_activity_logs USING btree (actor_user_id);


--
-- TOC entry 4156 (class 1259 OID 25378)
-- Name: idx_activity_logs_occurred_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_activity_logs_occurred_at ON public.tbl_activity_logs USING btree (occurred_at);


--
-- TOC entry 4157 (class 1259 OID 25376)
-- Name: idx_activity_logs_org; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_activity_logs_org ON public.tbl_activity_logs USING btree (org_id);


--
-- TOC entry 4135 (class 1259 OID 25306)
-- Name: idx_adp_org; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_adp_org ON public.tbl_analytics_daily_product USING btree (org_id);


--
-- TOC entry 4128 (class 1259 OID 25287)
-- Name: idx_ae_event_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ae_event_type ON public.tbl_analytics_events USING btree (event_type);


--
-- TOC entry 4129 (class 1259 OID 25286)
-- Name: idx_ae_occurred_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ae_occurred_at ON public.tbl_analytics_events USING btree (occurred_at);


--
-- TOC entry 4130 (class 1259 OID 25283)
-- Name: idx_ae_org; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ae_org ON public.tbl_analytics_events USING btree (org_id);


--
-- TOC entry 4131 (class 1259 OID 25284)
-- Name: idx_ae_product; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ae_product ON public.tbl_analytics_events USING btree (product_id);


--
-- TOC entry 4132 (class 1259 OID 25285)
-- Name: idx_ae_publish_link; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ae_publish_link ON public.tbl_analytics_events USING btree (publish_link_id);


--
-- TOC entry 4089 (class 1259 OID 25117)
-- Name: idx_assets_org; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assets_org ON public.tbl_assets USING btree (org_id);


--
-- TOC entry 4138 (class 1259 OID 25324)
-- Name: idx_authidentities_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_authidentities_user ON public.tbl_auth_identities USING btree (user_id);


--
-- TOC entry 4098 (class 1259 OID 25158)
-- Name: idx_configurators_product; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_configurators_product ON public.tbl_configurators USING btree (product_id);


--
-- TOC entry 4145 (class 1259 OID 25340)
-- Name: idx_emailver_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_emailver_user ON public.tbl_email_verifications USING btree (user_id);


--
-- TOC entry 4116 (class 1259 OID 25236)
-- Name: idx_galleries_org; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_galleries_org ON public.tbl_galleries USING btree (org_id);


--
-- TOC entry 4117 (class 1259 OID 25237)
-- Name: idx_galleries_public; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_galleries_public ON public.tbl_galleries USING btree (is_public);


--
-- TOC entry 4122 (class 1259 OID 25257)
-- Name: idx_gallery_items_gallery; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_gallery_items_gallery ON public.tbl_gallery_items USING btree (gallery_id);


--
-- TOC entry 4123 (class 1259 OID 25258)
-- Name: idx_gallery_items_product; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_gallery_items_product ON public.tbl_gallery_items USING btree (product_id);


--
-- TOC entry 4101 (class 1259 OID 25176)
-- Name: idx_hotspots_product; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_hotspots_product ON public.tbl_hotspots USING btree (product_id);


--
-- TOC entry 4106 (class 1259 OID 25200)
-- Name: idx_jobs_product; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_jobs_product ON public.tbl_jobs USING btree (product_id);


--
-- TOC entry 4107 (class 1259 OID 25201)
-- Name: idx_jobs_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_jobs_status ON public.tbl_jobs USING btree (status);


--
-- TOC entry 4084 (class 1259 OID 25103)
-- Name: idx_license_assignments_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_license_assignments_user ON public.tbl_license_assignments USING btree (user_id);


--
-- TOC entry 4160 (class 1259 OID 25394)
-- Name: idx_notifications_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_created ON public.tbl_notifications USING btree (created_at);


--
-- TOC entry 4161 (class 1259 OID 25395)
-- Name: idx_notifications_read; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_read ON public.tbl_notifications USING btree (read_at);


--
-- TOC entry 4162 (class 1259 OID 25393)
-- Name: idx_notifications_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_user ON public.tbl_notifications USING btree (user_id);


--
-- TOC entry 4073 (class 1259 OID 25050)
-- Name: idx_org_members_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_org_members_user ON public.tbl_org_members USING btree (user_id);


--
-- TOC entry 4150 (class 1259 OID 25356)
-- Name: idx_passwordresets_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_passwordresets_user ON public.tbl_password_resets USING btree (user_id);


--
-- TOC entry 4092 (class 1259 OID 25144)
-- Name: idx_products_creator; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_creator ON public.tbl_products USING btree (created_by);


--
-- TOC entry 4093 (class 1259 OID 25143)
-- Name: idx_products_org; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_org ON public.tbl_products USING btree (org_id);


--
-- TOC entry 4110 (class 1259 OID 25219)
-- Name: idx_publish_links_enabled; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_publish_links_enabled ON public.tbl_publish_links USING btree (is_enabled);


--
-- TOC entry 4111 (class 1259 OID 25218)
-- Name: idx_publish_links_product; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_publish_links_product ON public.tbl_publish_links USING btree (product_id);


--
-- TOC entry 4080 (class 1259 OID 25081)
-- Name: idx_subscriptions_plan; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_subscriptions_plan ON public.tbl_subscriptions USING btree (plan_id);


--
-- TOC entry 4081 (class 1259 OID 25080)
-- Name: idx_subscriptions_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_subscriptions_user ON public.tbl_subscriptions USING btree (user_id);


--
-- TOC entry 4231 (class 2606 OID 25366)
-- Name: tbl_activity_logs tbl_activity_logs_actor_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_activity_logs
    ADD CONSTRAINT tbl_activity_logs_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES public.tbl_users(id) ON DELETE SET NULL;


--
-- TOC entry 4232 (class 2606 OID 25613)
-- Name: tbl_activity_logs tbl_activity_logs_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_activity_logs
    ADD CONSTRAINT tbl_activity_logs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4233 (class 2606 OID 25371)
-- Name: tbl_activity_logs tbl_activity_logs_org_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_activity_logs
    ADD CONSTRAINT tbl_activity_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.tbl_organizations(id) ON DELETE SET NULL;


--
-- TOC entry 4234 (class 2606 OID 25619)
-- Name: tbl_activity_logs tbl_activity_logs_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_activity_logs
    ADD CONSTRAINT tbl_activity_logs_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4218 (class 2606 OID 25569)
-- Name: tbl_analytics_daily_product tbl_analytics_daily_product_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_analytics_daily_product
    ADD CONSTRAINT tbl_analytics_daily_product_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4219 (class 2606 OID 25296)
-- Name: tbl_analytics_daily_product tbl_analytics_daily_product_org_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_analytics_daily_product
    ADD CONSTRAINT tbl_analytics_daily_product_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.tbl_organizations(id) ON DELETE CASCADE;


--
-- TOC entry 4220 (class 2606 OID 25301)
-- Name: tbl_analytics_daily_product tbl_analytics_daily_product_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_analytics_daily_product
    ADD CONSTRAINT tbl_analytics_daily_product_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.tbl_products(id) ON DELETE CASCADE;


--
-- TOC entry 4221 (class 2606 OID 25575)
-- Name: tbl_analytics_daily_product tbl_analytics_daily_product_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_analytics_daily_product
    ADD CONSTRAINT tbl_analytics_daily_product_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4213 (class 2606 OID 25558)
-- Name: tbl_analytics_events tbl_analytics_events_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_analytics_events
    ADD CONSTRAINT tbl_analytics_events_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4214 (class 2606 OID 25268)
-- Name: tbl_analytics_events tbl_analytics_events_org_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_analytics_events
    ADD CONSTRAINT tbl_analytics_events_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.tbl_organizations(id) ON DELETE SET NULL;


--
-- TOC entry 4215 (class 2606 OID 25273)
-- Name: tbl_analytics_events tbl_analytics_events_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_analytics_events
    ADD CONSTRAINT tbl_analytics_events_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.tbl_products(id) ON DELETE SET NULL;


--
-- TOC entry 4216 (class 2606 OID 25278)
-- Name: tbl_analytics_events tbl_analytics_events_publish_link_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_analytics_events
    ADD CONSTRAINT tbl_analytics_events_publish_link_id_fkey FOREIGN KEY (publish_link_id) REFERENCES public.tbl_publish_links(id) ON DELETE SET NULL;


--
-- TOC entry 4217 (class 2606 OID 25564)
-- Name: tbl_analytics_events tbl_analytics_events_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_analytics_events
    ADD CONSTRAINT tbl_analytics_events_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4185 (class 2606 OID 25475)
-- Name: tbl_assets tbl_assets_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_assets
    ADD CONSTRAINT tbl_assets_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4186 (class 2606 OID 25112)
-- Name: tbl_assets tbl_assets_org_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_assets
    ADD CONSTRAINT tbl_assets_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.tbl_organizations(id) ON DELETE CASCADE;


--
-- TOC entry 4187 (class 2606 OID 25481)
-- Name: tbl_assets tbl_assets_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_assets
    ADD CONSTRAINT tbl_assets_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4222 (class 2606 OID 25580)
-- Name: tbl_auth_identities tbl_auth_identities_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_auth_identities
    ADD CONSTRAINT tbl_auth_identities_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4223 (class 2606 OID 25586)
-- Name: tbl_auth_identities tbl_auth_identities_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_auth_identities
    ADD CONSTRAINT tbl_auth_identities_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4224 (class 2606 OID 25319)
-- Name: tbl_auth_identities tbl_auth_identities_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_auth_identities
    ADD CONSTRAINT tbl_auth_identities_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.tbl_users(id) ON DELETE CASCADE;


--
-- TOC entry 4192 (class 2606 OID 25492)
-- Name: tbl_configurators tbl_configurators_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_configurators
    ADD CONSTRAINT tbl_configurators_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4193 (class 2606 OID 25153)
-- Name: tbl_configurators tbl_configurators_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_configurators
    ADD CONSTRAINT tbl_configurators_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.tbl_products(id) ON DELETE CASCADE;


--
-- TOC entry 4194 (class 2606 OID 25498)
-- Name: tbl_configurators tbl_configurators_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_configurators
    ADD CONSTRAINT tbl_configurators_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4225 (class 2606 OID 25591)
-- Name: tbl_email_verifications tbl_email_verifications_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_email_verifications
    ADD CONSTRAINT tbl_email_verifications_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4226 (class 2606 OID 25597)
-- Name: tbl_email_verifications tbl_email_verifications_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_email_verifications
    ADD CONSTRAINT tbl_email_verifications_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4227 (class 2606 OID 25335)
-- Name: tbl_email_verifications tbl_email_verifications_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_email_verifications
    ADD CONSTRAINT tbl_email_verifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.tbl_users(id) ON DELETE CASCADE;


--
-- TOC entry 4206 (class 2606 OID 25536)
-- Name: tbl_galleries tbl_galleries_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_galleries
    ADD CONSTRAINT tbl_galleries_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4207 (class 2606 OID 25231)
-- Name: tbl_galleries tbl_galleries_org_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_galleries
    ADD CONSTRAINT tbl_galleries_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.tbl_organizations(id) ON DELETE CASCADE;


--
-- TOC entry 4208 (class 2606 OID 25542)
-- Name: tbl_galleries tbl_galleries_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_galleries
    ADD CONSTRAINT tbl_galleries_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4209 (class 2606 OID 25547)
-- Name: tbl_gallery_items tbl_gallery_items_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_gallery_items
    ADD CONSTRAINT tbl_gallery_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4210 (class 2606 OID 25247)
-- Name: tbl_gallery_items tbl_gallery_items_gallery_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_gallery_items
    ADD CONSTRAINT tbl_gallery_items_gallery_id_fkey FOREIGN KEY (gallery_id) REFERENCES public.tbl_galleries(id) ON DELETE CASCADE;


--
-- TOC entry 4211 (class 2606 OID 25252)
-- Name: tbl_gallery_items tbl_gallery_items_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_gallery_items
    ADD CONSTRAINT tbl_gallery_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.tbl_products(id) ON DELETE CASCADE;


--
-- TOC entry 4212 (class 2606 OID 25553)
-- Name: tbl_gallery_items tbl_gallery_items_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_gallery_items
    ADD CONSTRAINT tbl_gallery_items_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4195 (class 2606 OID 25503)
-- Name: tbl_hotspots tbl_hotspots_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_hotspots
    ADD CONSTRAINT tbl_hotspots_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4196 (class 2606 OID 25171)
-- Name: tbl_hotspots tbl_hotspots_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_hotspots
    ADD CONSTRAINT tbl_hotspots_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.tbl_products(id) ON DELETE CASCADE;


--
-- TOC entry 4197 (class 2606 OID 25509)
-- Name: tbl_hotspots tbl_hotspots_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_hotspots
    ADD CONSTRAINT tbl_hotspots_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4198 (class 2606 OID 25514)
-- Name: tbl_jobs tbl_jobs_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_jobs
    ADD CONSTRAINT tbl_jobs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4199 (class 2606 OID 25190)
-- Name: tbl_jobs tbl_jobs_image_asset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_jobs
    ADD CONSTRAINT tbl_jobs_image_asset_id_fkey FOREIGN KEY (image_asset_id) REFERENCES public.tbl_assets(id) ON DELETE SET NULL;


--
-- TOC entry 4200 (class 2606 OID 25195)
-- Name: tbl_jobs tbl_jobs_model_asset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_jobs
    ADD CONSTRAINT tbl_jobs_model_asset_id_fkey FOREIGN KEY (model_asset_id) REFERENCES public.tbl_assets(id) ON DELETE SET NULL;


--
-- TOC entry 4201 (class 2606 OID 25185)
-- Name: tbl_jobs tbl_jobs_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_jobs
    ADD CONSTRAINT tbl_jobs_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.tbl_products(id) ON DELETE CASCADE;


--
-- TOC entry 4202 (class 2606 OID 25520)
-- Name: tbl_jobs tbl_jobs_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_jobs
    ADD CONSTRAINT tbl_jobs_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4181 (class 2606 OID 25464)
-- Name: tbl_license_assignments tbl_license_assignments_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_license_assignments
    ADD CONSTRAINT tbl_license_assignments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4182 (class 2606 OID 25093)
-- Name: tbl_license_assignments tbl_license_assignments_subscription_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_license_assignments
    ADD CONSTRAINT tbl_license_assignments_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.tbl_subscriptions(id) ON DELETE CASCADE;


--
-- TOC entry 4183 (class 2606 OID 25470)
-- Name: tbl_license_assignments tbl_license_assignments_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_license_assignments
    ADD CONSTRAINT tbl_license_assignments_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4184 (class 2606 OID 25098)
-- Name: tbl_license_assignments tbl_license_assignments_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_license_assignments
    ADD CONSTRAINT tbl_license_assignments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.tbl_users(id) ON DELETE CASCADE;


--
-- TOC entry 4175 (class 2606 OID 25453)
-- Name: tbl_mstr_plans tbl_mstr_plans_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_mstr_plans
    ADD CONSTRAINT tbl_mstr_plans_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4176 (class 2606 OID 25459)
-- Name: tbl_mstr_plans tbl_mstr_plans_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_mstr_plans
    ADD CONSTRAINT tbl_mstr_plans_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4235 (class 2606 OID 25624)
-- Name: tbl_notifications tbl_notifications_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_notifications
    ADD CONSTRAINT tbl_notifications_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4236 (class 2606 OID 25630)
-- Name: tbl_notifications tbl_notifications_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_notifications
    ADD CONSTRAINT tbl_notifications_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4237 (class 2606 OID 25388)
-- Name: tbl_notifications tbl_notifications_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_notifications
    ADD CONSTRAINT tbl_notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.tbl_users(id) ON DELETE CASCADE;


--
-- TOC entry 4171 (class 2606 OID 25431)
-- Name: tbl_org_members tbl_org_members_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_org_members
    ADD CONSTRAINT tbl_org_members_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4172 (class 2606 OID 25040)
-- Name: tbl_org_members tbl_org_members_org_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_org_members
    ADD CONSTRAINT tbl_org_members_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.tbl_organizations(id) ON DELETE CASCADE;


--
-- TOC entry 4173 (class 2606 OID 25437)
-- Name: tbl_org_members tbl_org_members_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_org_members
    ADD CONSTRAINT tbl_org_members_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4174 (class 2606 OID 25045)
-- Name: tbl_org_members tbl_org_members_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_org_members
    ADD CONSTRAINT tbl_org_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.tbl_users(id) ON DELETE CASCADE;


--
-- TOC entry 4169 (class 2606 OID 25420)
-- Name: tbl_organizations tbl_organizations_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_organizations
    ADD CONSTRAINT tbl_organizations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4170 (class 2606 OID 25426)
-- Name: tbl_organizations tbl_organizations_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_organizations
    ADD CONSTRAINT tbl_organizations_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4228 (class 2606 OID 25602)
-- Name: tbl_password_resets tbl_password_resets_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_password_resets
    ADD CONSTRAINT tbl_password_resets_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4229 (class 2606 OID 25608)
-- Name: tbl_password_resets tbl_password_resets_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_password_resets
    ADD CONSTRAINT tbl_password_resets_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4230 (class 2606 OID 25351)
-- Name: tbl_password_resets tbl_password_resets_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_password_resets
    ADD CONSTRAINT tbl_password_resets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.tbl_users(id) ON DELETE CASCADE;


--
-- TOC entry 4188 (class 2606 OID 25138)
-- Name: tbl_products tbl_products_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_products
    ADD CONSTRAINT tbl_products_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.tbl_users(id) ON DELETE SET NULL;


--
-- TOC entry 4189 (class 2606 OID 25133)
-- Name: tbl_products tbl_products_model_asset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_products
    ADD CONSTRAINT tbl_products_model_asset_id_fkey FOREIGN KEY (model_asset_id) REFERENCES public.tbl_assets(id) ON DELETE SET NULL;


--
-- TOC entry 4190 (class 2606 OID 25128)
-- Name: tbl_products tbl_products_org_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_products
    ADD CONSTRAINT tbl_products_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.tbl_organizations(id) ON DELETE CASCADE;


--
-- TOC entry 4191 (class 2606 OID 25487)
-- Name: tbl_products tbl_products_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_products
    ADD CONSTRAINT tbl_products_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4203 (class 2606 OID 25525)
-- Name: tbl_publish_links tbl_publish_links_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_publish_links
    ADD CONSTRAINT tbl_publish_links_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4204 (class 2606 OID 25213)
-- Name: tbl_publish_links tbl_publish_links_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_publish_links
    ADD CONSTRAINT tbl_publish_links_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.tbl_products(id) ON DELETE CASCADE;


--
-- TOC entry 4205 (class 2606 OID 25531)
-- Name: tbl_publish_links tbl_publish_links_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_publish_links
    ADD CONSTRAINT tbl_publish_links_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4177 (class 2606 OID 25442)
-- Name: tbl_subscriptions tbl_subscriptions_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_subscriptions
    ADD CONSTRAINT tbl_subscriptions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4178 (class 2606 OID 25075)
-- Name: tbl_subscriptions tbl_subscriptions_plan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_subscriptions
    ADD CONSTRAINT tbl_subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.tbl_mstr_plans(id) ON DELETE RESTRICT;


--
-- TOC entry 4179 (class 2606 OID 25448)
-- Name: tbl_subscriptions tbl_subscriptions_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_subscriptions
    ADD CONSTRAINT tbl_subscriptions_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4180 (class 2606 OID 25070)
-- Name: tbl_subscriptions tbl_subscriptions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_subscriptions
    ADD CONSTRAINT tbl_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.tbl_users(id) ON DELETE CASCADE;


--
-- TOC entry 4238 (class 2606 OID 25635)
-- Name: tbl_user_notification_prefs tbl_user_notification_prefs_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_user_notification_prefs
    ADD CONSTRAINT tbl_user_notification_prefs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4239 (class 2606 OID 25641)
-- Name: tbl_user_notification_prefs tbl_user_notification_prefs_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_user_notification_prefs
    ADD CONSTRAINT tbl_user_notification_prefs_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4240 (class 2606 OID 25403)
-- Name: tbl_user_notification_prefs tbl_user_notification_prefs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_user_notification_prefs
    ADD CONSTRAINT tbl_user_notification_prefs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.tbl_users(id) ON DELETE CASCADE;


--
-- TOC entry 4167 (class 2606 OID 25409)
-- Name: tbl_users tbl_users_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_users
    ADD CONSTRAINT tbl_users_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.tbl_users(id);


--
-- TOC entry 4168 (class 2606 OID 25415)
-- Name: tbl_users tbl_users_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_users
    ADD CONSTRAINT tbl_users_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.tbl_users(id);


-- Completed on 2025-11-04 17:16:23 IST


--
-- Name: notify_product_status_change(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE OR REPLACE FUNCTION public.notify_product_status_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    -- IS DISTINCT FROM handles NULL safely, unlike !=
    IF OLD.status IS DISTINCT FROM NEW.status THEN
        PERFORM pg_notify(
            'tbl_product_status',
            json_build_object(
                'product_id',   NEW.id,
                'old_status',   OLD.status,
                'new_status',   NEW.status,
                'updated_date', NEW.updated_date
            )::text
        );
    END IF;
    RETURN NEW;
END;
$$;


--
-- Name: product_status_changed; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER product_status_changed
AFTER UPDATE ON public.tbl_products
FOR EACH ROW EXECUTE FUNCTION public.notify_product_status_change();


--
-- PostgreSQL database dump complete
--

