"""add Product Configurator tables: parts, options, option textures

Revision ID: c7a4e0d51b83
Revises: b8e2f4a10c73
Create Date: 2026-09-08 00:00:00.000000

Three tables, created as one unit because a partial application helps nobody:

    tbl_product_parts         a seller-named region of a product, owning a set
                              of glTF material indices from the original GLB
    tbl_part_options          a shopper-selectable appearance for that part;
                              `recipe` covers both a generated recolour and an
                              uploaded texture, discriminated by recipe.method
    tbl_part_option_textures  the baked texture each option produces per
                              material index — pure cache, regenerable

Written by hand, not autogenerated. migrations/env.py installs an
include_object hook that refuses to autogenerate foreign keys at all (43
undeclared audit FKs would otherwise be emitted as DROPs), and its docstring
records that this schema has drifted from the migration chain badly enough that
autogenerate output always needs reading line by line.

pgcrypto is NOT created here — 6317c2563d0b already did it, so
gen_random_uuid() is available.

NO FOREIGN KEY from created_by / updated_by to tbl_users — deliberate, and
load-bearing
--------------------------------------------------------------------------
ACCOUNT_PURGE_JOB_HANDOFF.md section 25 specifies a schema contract check run
before every purge, whose assertion 9 aborts the entire run if an unexpected
new foreign key references tbl_users. Adding one here would break a production
job in another repository. AuditMixin declares these columns as plain UUIDs for
exactly this reason; the same choice is documented at app/models/login_otp.py.

The ONE new FK to tbl_products (tbl_product_parts.product_id) is kept, because
the purge deletes products before their owner and a missing cascade would make
that DELETE fail outright — the same failure revision b3f8d21c4a76 exists to
fix. That FK is a KNOWN addition and Rivollo.AccountPurge.Job must allow-list it
in assertion 9, add all three tables to its cascade inventory, and add the
`configurator/{product_id}/...` blob prefix to its deletion order BEFORE this
migration reaches production. See docs/configurator/decisions.md ADR-010.

No circular foreign key to sequence: the default option is a boolean on
tbl_part_options guarded by a partial unique index, not a default_option_id
pointer on the part (ADR-011), so a single upgrade() body suffices.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "c7a4e0d51b83"
down_revision: Union[str, Sequence[str], None] = "b8e2f4a10c73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _audit_columns() -> list[sa.Column]:
    """The four AuditMixin columns, with NO FK to tbl_users. See the docstring."""
    return [
        sa.Column("created_by", postgresql.UUID(as_uuid=True)),
        sa.Column(
            "created_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", postgresql.UUID(as_uuid=True)),
        sa.Column("updated_date", sa.TIMESTAMP(timezone=True)),
    ]


def upgrade() -> None:
    """Create the three Configurator tables."""

    # ---------------------------------------------------------------- parts
    op.create_table(
        "tbl_product_parts",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("product_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        # glTF material indices, e.g. [0, 3, 7]. No JSONB CHECK: shape is a
        # Pydantic concern and no other JSONB column in this schema carries one.
        sa.Column(
            "material_indices",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("material_type", sa.Text()),
        sa.Column("order_index", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "shopper_selectable",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        # Prefix-discriminated ("asset:<uuid>" / "sha256:<hex>") so the identity
        # strategy can change by data migration. ADR-006 is Needs Verification.
        sa.Column("glb_version", sa.Text(), nullable=False),
        sa.Column("isactive", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        *_audit_columns(),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["tbl_products.id"],
            name="fk_parts_product",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("product_id", "slug", name="uq_parts_product_slug"),
    )
    op.create_index("ix_parts_product_order", "tbl_product_parts", ["product_id", "order_index"])
    # The shopper payload reads exactly this slice.
    op.create_index(
        "ix_parts_product_active",
        "tbl_product_parts",
        ["product_id"],
        postgresql_where=sa.text("isactive AND shopper_selectable"),
    )

    # -------------------------------------------------------------- options
    op.create_table(
        "tbl_part_options",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("part_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("swatch_hex", sa.Text(), nullable=False),
        # Both option kinds live here, discriminated by recipe.method:
        #   {"version":1,"method":"luminance","color":"#C0182B","brightness":1.0}
        #   {"version":1,"method":"image","image_url":"https://cdn/..."}
        sa.Column(
            "recipe",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("recipe_hash", sa.Text(), nullable=False),
        sa.Column("order_index", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("isactive", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "bake_status", sa.Text(), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("bake_error", sa.Text()),
        sa.Column("bake_started_at", sa.TIMESTAMP(timezone=True)),
        sa.Column("bake_completed_at", sa.TIMESTAMP(timezone=True)),
        sa.Column("bake_attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        *_audit_columns(),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["tbl_product_parts.id"],
            name="fk_options_part",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("part_id", "slug", name="uq_options_part_slug"),
        sa.CheckConstraint("swatch_hex ~* '^#[0-9A-F]{6}$'", name="ck_options_swatch_hex"),
        sa.CheckConstraint(
            "bake_status IN ('pending', 'baking', 'completed', 'failed')",
            name="ck_options_bake_status",
        ),
    )
    op.create_index("ix_options_part_order", "tbl_part_options", ["part_id", "order_index"])
    # At most ONE default per part, enforced by the database rather than by
    # code — same shape as ux_color_variants_one_default.
    op.create_index(
        "ux_part_options_one_default",
        "tbl_part_options",
        ["part_id"],
        unique=True,
        postgresql_where=sa.text("is_default"),
    )
    # Sized to the in-flight bakes only, so the stale-bake sweep is free.
    op.create_index(
        "ix_options_stale",
        "tbl_part_options",
        ["bake_started_at"],
        postgresql_where=sa.text("bake_status = 'baking'"),
    )

    # ------------------------------------------------------------- textures
    op.create_table(
        "tbl_part_option_textures",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("option_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("material_index", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("blob_url", sa.Text()),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("width", sa.Integer()),
        sa.Column("height", sa.Integer()),
        sa.Column("size_bytes", sa.BigInteger()),
        # Must equal the parent option's. If it does not, this file was baked
        # from a superseded recipe and must not be served.
        sa.Column("recipe_hash", sa.Text(), nullable=False),
        *_audit_columns(),
        sa.ForeignKeyConstraint(
            ["option_id"],
            ["tbl_part_options.id"],
            name="fk_option_textures_option",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("option_id", "material_index", name="uq_option_texture_material"),
        sa.CheckConstraint("material_index >= 0", name="ck_option_texture_index"),
        sa.CheckConstraint(
            "content_type IN ('image/png', 'image/jpeg')", name="ck_option_texture_mime"
        ),
    )
    op.create_index("ix_option_textures_option", "tbl_part_option_textures", ["option_id"])


def downgrade() -> None:
    """Drop in reverse dependency order: textures -> options -> parts."""
    op.drop_index("ix_option_textures_option", table_name="tbl_part_option_textures")
    op.drop_table("tbl_part_option_textures")

    op.drop_index("ix_options_stale", table_name="tbl_part_options")
    op.drop_index("ux_part_options_one_default", table_name="tbl_part_options")
    op.drop_index("ix_options_part_order", table_name="tbl_part_options")
    op.drop_table("tbl_part_options")

    op.drop_index("ix_parts_product_active", table_name="tbl_product_parts")
    op.drop_index("ix_parts_product_order", table_name="tbl_product_parts")
    op.drop_table("tbl_product_parts")
